apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kafka-streams.fullname" . }}-sender
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka-streams.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-kafka-in-topic-ready
          image: "alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              apk add kafkacat && until [ $(kafkacat -L -b {{ printf "%s://%s:%s" (.Values.kafka.auth.clientProtocol) (include "kafka.fullname" . ) ( .Values.kafka.service.port | toString ) | quote }} | grep -E 'topic\s\"({{ .Values.application.kafka.inTopicName }})\"' | wc -l ) -eq 1 ]; do echo waiting for kafka initialization; sleep 2; done
      containers:
        - name: {{ .Chart.Name }}-sender
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BOOTSTRAP_SERVERS_CONFIG
              value: {{ printf "%s://%s:%s" (.Values.kafka.auth.clientProtocol) (include "kafka.fullname" . ) ( .Values.kafka.service.port | toString ) | quote }}
            - name: SENDER_MODE
              value: "1"
            - name: IN_TOPIC_NAME
              value: {{ .Values.application.kafka.inTopicName | quote }}
            - name: SENDER_CHUNK_CNT
              value: {{ .Values.application.sender.chunkCnt | quote }}
            - name: SENDER_CHUNK_SIZE
              value: {{ .Values.application.sender.chunkSize | quote }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}