{{- $jmxParams := .Values.application.jmxRemote -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-streams.fullname" . }}-metrics-cm
data:
  metrics.yaml: |
    jmxUrl: {{ printf "service:jmx:rmi:///jndi/rmi://%s:%s/jmxrmi" $jmxParams.url ( $jmxParams.port | toString ) | quote }}
    {{- with .Values.application.jmxExport.config }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-streams.fullname" . }}-logging-cm
data:
  logging.properties: |
    handlers=java.util.logging.ConsoleHandler
    java.util.logging.ConsoleHandler.level=INFO
    io.prometheus.jmx.level=WARNING
    io.prometheus.jmx.shaded.io.prometheus.jmx.level=WARNING