{{- $configParams := .Values.application.jmxExport.params -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-streams.fullname" . }}-metrics-cm
data:
  metrics.yaml: |
    jmxUrl: {{ printf "service:jmx:rmi:///jndi/rmi://%s:%s/%s" $configParams.url ( $configParams.port | toString ) $configParams.rmi | quote }}
    startDelaySeconds: {{ $configParams.startDelaySeconds | default 0 }}
    lowercaseOutputName: {{ $configParams.lowercaseOutputName | default true }}
    lowercaseOutputLabelNames: {{ $configParams.lowercaseOutputLabelNames | default true }}
    ssl: {{ $configParams.ssl | default false }}
    {{- if $configParams.whitelistObjectNames }}
    whitelistObjectNames: ["{{ join "\",\"" $configParams.whitelistObjectNames }}"]
    {{- end }}
    {{- if $configParams.blacklistObjectNames }}
    blacklistObjectNames: ["{{ join "\",\"" $configParams.blacklistObjectNames }}"]
    {{- end }}
    {{- if $configParams.rules }}
    rules:
      {{- range $configParams.rules }}
        {{- toYaml .Values.resources | nindent 2 }}
      {{- end }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-streams.fullname" . }}-logging-cm
data:
  logging.properties: |
    handlers=java.util.logging.ConsoleHandler
    java.util.logging.ConsoleHandler.level=INFO
    io.prometheus.jmx.level=WARNING
    io.prometheus.jmx.shaded.io.prometheus.jmx.level=WARNING