prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana-dashboard
  adminPassword: prom-operator
  persistence:
    enabled: true